### ISSUE TITLE
allow for secondary grouping of federal stations in the mapping module

### ISSUE THREAD

**Issue by smwatson** [GCOOS/dataPortal#1]
to allow for easier searching for obs by observing programs (e.g., PORTS, Sentinels, Co-Ops tides/met) within federal agencies, such as NOS, etc.

**Comment by fgayanilo** [comment]
A review of the stations will commence later this week to see what secondary groupings are available for NERRS, NOS and NDBC.

**Comment by mkhoward** [comment]
NERRS are ok as is
Sentinel and PORTS should be finefor now.

Phone sent

On Oct 12, 2015, at 3:03 PM, Felimon Gayanilo <notifications@github.com<mailto:notifications@github.com>> wrote:


A review of the stations will commence later this week to see what secondary groupings are available for NERRS, NOS and NDBC.

**Comment by fgayanilo** [comment]
A new WAF has been published (http://data.gcoos.org/waf). It now contains a summary of data by observation, or by platform (station). Moreover, the data were segregated by data source, i.e. from federal sources or from GCOOS Local Data Nodes.

**Comment by mkhoward** [comment]
I downloaded it yesterday and have started crunching

Phone sent

On Apr 26, 2016, at 3:00 PM, Felimon Gayanilo <notifications@github.com<mailto:notifications@github.com>> wrote:


A new WAF has been published (http://data.gcoos.org/waf). It now contains a summary of data by observation, or by platform (station). Moreover, the data were segregated by data source, i.e. from federal sources or from GCOOS Local Data Nodes.
